version: '3'
services:
        singlecell-environment:
                image: gnasello/sc-env:latest
                ports:
                 - 8888:8888
                volumes:
                 - /home/luna.kuleuven.be/u0128401:/root/host_home
                working_dir: '/root/host_home'
                container_name:   singlecell-environment