name: sc-env
channels:
 - conda-forge
 - bioconda
dependencies:
# - r-base
 - r-essentials
 - r-devtools
 - r-biocmanager
 - r-rcolorbrewer
 - r-remotes
 - r-seurat 
 - r-patchwork
 - r-monocle3
 - bioconductor-scater
# - anndata==0.6.19 
# - scipy==1.2.1
# - r-reticulate
# - loompy
# - r-sceasy
 - numba==0.52.0
 - jupyterlab
 - jupyter_contrib_nbextensions
 - louvain==0.7
 - umap-learn==0.4.6
 - pandas==1.2.5
 - scanpy
 - python-igraph
 - leidenalg
 - rpy2
 - anndata2ri
 - multicore-tsne
 - scvelo
 - pip
