name: sc-env
channels:
 - conda-forge
 - bioconda
dependencies:
 - r-essentials
 - r-devtools
 - r-biocmanager
 - r-rcolorbrewer
 - r-remotes
 - r-svglite
 - r-latex2exp
 - r-r.utils
 - r-rstatix
 - r-ggpubr
 - r-ggsci
 - r-repr
 - r-seurat 
 - r-patchwork
 - r-monocle3
 - bioconductor-scater
 - numba==0.52.0
 - jupyterlab
 - jupyter_contrib_nbextensions
 - louvain==0.7
 - umap-learn==0.4.6
 - pandas==1.2.5
 - scanpy
 - python-igraph
 - leidenalg
 - rpy2
 - anndata2ri
 - multicore-tsne
 - scvelo
 - opentsne
 - plotly
 - pip
 - pip:
   - lckr-jupyterlab-variableinspector
